version: "3.8"

services:
  postgres:
    # Database URL for this specific configuration: postgresql://admin:123123@localhost:5432/postgres
    image: postgres:15.2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=postgres
    restart: always

  meilisearch:
    image: "getmeili/meilisearch:v1.11"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    ports:
      - "7700:7700"
    restart: always
    volumes:
      - ./meilisearch:/meili_data

volumes:
  postgres-data:
